"""CSV and PDF renderers for generated reports (session 6.2).

**PDF is pure Python (reportlab).** The platform deliberately does not shell out
to wkhtmltopdf: report rendering happens inside the control plane, and a managed
server is not a rendering appliance. reportlab has no system-library
dependencies (unlike weasyprint's cairo/pango), so the platform installs
cleanly on a bare Ubuntu box — which is the whole premise of the installer.

Both renderers emit the **evidence header** for a report declared
`evidence=True` (uiux-spec A1.6): generation timestamp, generating user, the
explicit date range, and the row count, so the artifact stands on its own when
it leaves the platform.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Iterator
from datetime import datetime
from typing import Any

from app.core.reports.registry import ReportDef, ReportResult

# Rendered into every artifact header so a reader knows which timezone the
# human-readable instants are in (golden rule 8).
DISPLAY_TZ_NOTE = "Timestamps are UTC unless a timezone offset is shown."

# Leading characters a spreadsheet (Excel/LibreOffice) may interpret as a
# formula on open — the CSV-injection vector (CWE-1236). These evidence exports
# leave the platform by email to auditors, and cells carry user-controlled
# values (site/domain/server names, sanitized params, user email/full name), so
# every emitted cell is neutralised before it is written.
_CSV_FORMULA_LEADERS = ("=", "+", "-", "@")


def _csv_safe(value: Any) -> str:
    """Neutralise a cell that a spreadsheet could execute as a formula.

    Prefixes a single quote when the stringified value begins with a formula
    leader (`= + - @`) or a leading tab/CR/newline. Legitimate numbers (e.g. a
    negative headroom `-5`) are left untouched so numeric columns stay numeric —
    only values that do not parse as a number are quoted.
    """
    text = "" if value is None else str(value)
    if not text:
        return text
    first = text[0]
    if first in ("\t", "\r", "\n"):
        return "'" + text
    if first in _CSV_FORMULA_LEADERS:
        try:
            float(text)
        except ValueError:
            return "'" + text
    return text


def _evidence_lines(
    report: ReportDef,
    result: ReportResult,
    *,
    generated_at: datetime,
    generated_by: str,
    params: dict[str, Any],
    window: tuple[datetime, datetime] | None,
) -> list[tuple[str, str]]:
    """The self-describing header every artifact carries."""
    lines = [
        ("Report", report.title),
        ("Generated at", generated_at.isoformat(timespec="seconds")),
        ("Generated by", generated_by),
    ]
    if window is not None:
        start, end = window
        lines.append(
            (
                "Date range",
                f"{start.isoformat(timespec='seconds')} .. {end.isoformat(timespec='seconds')}",
            )
        )
    else:
        lines.append(("Date range", "point-in-time (not range-scoped)"))
    lines.append(("Rows", str(result.row_count)))
    if params:
        lines.append(
            ("Parameters", ", ".join(f"{k}={v}" for k, v in sorted(params.items())))
        )
    return lines


def render_csv(
    report: ReportDef,
    result: ReportResult,
    *,
    generated_at: datetime,
    generated_by: str,
    params: dict[str, Any],
    window: tuple[datetime, datetime] | None = None,
) -> Iterator[str]:
    """Yield the CSV a chunk at a time.

    Streaming (rather than building one string) keeps a large job-history export
    off the heap — the API hands this straight to a StreamingResponse and the
    worker writes it to disk row by row.
    """
    header = _evidence_lines(
        report,
        result,
        generated_at=generated_at,
        generated_by=generated_by,
        params=params,
        window=window,
    )
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")

    def _drain() -> str:
        chunk = buffer.getvalue()
        buffer.seek(0)
        buffer.truncate(0)
        return chunk

    # `# ` prefixes keep the metadata block from being mistaken for data by a
    # spreadsheet import while staying human-readable in a plain text editor.
    # The label column is already `#`-prefixed; the value column is neutralised
    # because it carries user-controlled text (generated-by email, parameters).
    for label, value in header:
        writer.writerow([f"# {label}", _csv_safe(value)])
    for label, value in result.summary:
        writer.writerow([f"# {label}", _csv_safe(value)])
    writer.writerow([])
    yield _drain()

    writer.writerow([_csv_safe(head) for _, head in result.columns])
    yield _drain()

    for row in result.rows:
        writer.writerow([_csv_safe(row.get(key, "")) for key, _ in result.columns])
        chunk = _drain()
        if chunk:
            yield chunk


def render_pdf(
    report: ReportDef,
    result: ReportResult,
    *,
    generated_at: datetime,
    generated_by: str,
    params: dict[str, Any],
    window: tuple[datetime, datetime] | None = None,
) -> bytes:
    """Render a landscape A4 PDF: evidence header, summary block, then the table.

    Wide reports (job history has ten columns) are landscape and the table is
    laid out on the available width, so a column is never silently cut off at
    the page edge.
    """
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buffer = io.BytesIO()
    page_size = landscape(A4)
    doc = SimpleDocTemplate(
        buffer,
        pagesize=page_size,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
        title=report.title,
        author=generated_by,
        subject=report.description,
    )
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle(
        "cell", parent=styles["BodyText"], fontSize=7, leading=8.5, alignment=TA_LEFT
    )
    head_style = ParagraphStyle(
        "head", parent=cell_style, fontName="Helvetica-Bold", textColor=colors.white
    )

    story: list[Any] = [
        Paragraph(report.title, styles["Title"]),
        Paragraph(report.description, styles["Italic"]),
        Spacer(1, 6 * mm),
    ]

    meta = _evidence_lines(
        report,
        result,
        generated_at=generated_at,
        generated_by=generated_by,
        params=params,
        window=window,
    )
    meta_table = Table(
        [[Paragraph(f"<b>{label}</b>", cell_style), Paragraph(str(value), cell_style)]
         for label, value in meta],
        colWidths=[45 * mm, doc.width - 45 * mm],
        hAlign="LEFT",
    )
    meta_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F4F4F5")),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story += [meta_table, Spacer(1, 5 * mm)]

    if result.summary:
        story.append(Paragraph("Summary", styles["Heading3"]))
        summary_table = Table(
            [[Paragraph(f"<b>{label}</b>", cell_style), Paragraph(str(value), cell_style)]
             for label, value in result.summary],
            colWidths=[60 * mm, 60 * mm],
            hAlign="LEFT",
        )
        summary_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story += [summary_table, Spacer(1, 5 * mm)]

    if result.note:
        story += [Paragraph(result.note, styles["Italic"]), Spacer(1, 4 * mm)]

    story.append(Paragraph(f"{report.title} — rows", styles["Heading3"]))

    if not result.rows:
        story.append(Paragraph("No rows matched this report's parameters.", cell_style))
    else:
        data = [[Paragraph(head, head_style) for _, head in result.columns]]
        for row in result.rows:
            data.append(
                [Paragraph(_escape(row.get(key, "")), cell_style) for key, _ in result.columns]
            )
        col_width = doc.width / len(result.columns)
        table = Table(
            data,
            colWidths=[col_width] * len(result.columns),
            repeatRows=1,
            hAlign="LEFT",
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#232326")),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 3),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 2),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#FAFAFA")],
                    ),
                ]
            )
        )
        story.append(table)

    story += [Spacer(1, 4 * mm), Paragraph(DISPLAY_TZ_NOTE, styles["Italic"])]
    doc.build(story)
    return buffer.getvalue()


def _escape(value: Any) -> str:
    """Make a cell value safe for reportlab's mini-HTML paragraph markup.

    A site name or job parameter can legitimately contain `&` or `<`; without
    escaping, reportlab would either raise or swallow the rest of the cell.
    """
    text = "" if value is None else str(value)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


__all__ = ["render_csv", "render_pdf"]
