"""server registry: servers, ssh_credentials

Revision ID: 0cdc7d2ec643
Revises: 4398322a0b03
Create Date: 2026-07-09 23:25:43.866959

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401 — used by generated operations
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '0cdc7d2ec643'
down_revision: str | Sequence[str] | None = '4398322a0b03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('env_tag', sa.String(length=10), nullable=False),
    sa.Column(
        'tags',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
        nullable=False,
    ),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_table('ssh_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('auth_type', sa.String(length=10), nullable=False),
    sa.Column('private_key_enc', sa.Text(), nullable=True),
    sa.Column('passphrase_enc', sa.Text(), nullable=True),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('known_host_key', sa.Text(), nullable=True),
    sa.Column('sudo_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssh_credentials_server_id'), 'ssh_credentials', ['server_id'],
                    unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssh_credentials_server_id'), table_name='ssh_credentials')
    op.drop_table('ssh_credentials')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
